### ISSUE TITLE
レーザーが一定時間おきにチカチカするようにしたい！

### ISSUE THREAD

**Issue by mikushimizu** [mikushimizu/HelloWorld#1]
レーザーオブジェクトがついたり消えたりして、消えてるタイミングに抜けないとゲームオーバーになるというふうにしたいです。

今、レーザーオブジェに当たるとゲームオーバーになるところまでは作りました。
レーザーオブジェにレーザースクリプトをつけて、レーザースクリプトに、レーザーが見えたり消えたりするのを繰り返し続ける命令を書きたいです。
SetActiveやenabledをwhile(true)で囲ったりしてみたのですが思うように動きません。
どうすればいいでしょうか…！

**Comment by Junichi0227** [comment]
一番楽なのはanimationでCollisionとMesh RendererのOn/Offもできるのでそれをすると楽にできると思います！一応gifも載せておきますねー

本当はanimationでSetActiveのon/offをさせたかったのですが、できなかったので上の方法で試してみてくださいねー

**Comment by Ayarin226** [comment]
Start()でコルーチンを呼び出して、1秒起きとかに表示非表示を反転させれば良いと思います。

```
yield return new WaitFor Seconds(1.0f);
flag = !flag;
gameObject.SetActive(flag);
```

こんなイメージで出来るかと。

**Comment by Ayarin226** [comment]
コルーチンについてはチーム課題でも少し触れています！
詳しくは調べてみてください🙏🏻

**Comment by Junichi0227** [comment]
![help](https://user-images.githubusercontent.com/19296898/39533076-263065a2-4e69-11e8-866d-869e773cfaf9.gif)

**Comment by Junichi0227** [comment]
一応こういう感じですー！

**Comment by mikushimizu** [comment]
できました！！！ありがとうございました！
