### ISSUE TITLE
セーブ機能作りたい

### ISSUE THREAD

**Issue by mikushimizu** [mikushimizu/HelloWorld#2]
青いパーティクルに触れると、その地点とその時点の制限時間が記録され、ゲームオーバー画面からRestartするとその地点とその時点の制限時間から始められるようにしたいです。
どうコード書けばいいかわかりません…！

**Comment by Ayarin226** [comment]
原理としてはチーム課題とおんなじかと！
チーム課題では位置だけだったのを時間も記録してあげればOK
完全に一文も書けない？
どこまで分かっていてどこからが難しいか教えて貰えると具体的にアドバイス出来るかも！

**Comment by mikushimizu** [comment]
チーム課題もう一度見直してみます…！

**Comment by Ayarin226** [comment]
そのためのチーム課題でもあるので是非！
見直しても難しかったらいつでも聞いてくださいね🙌🏻
