### ISSUE TITLE
プレイヤーの動きを調整したい

### ISSUE THREAD

**Issue by mikushimizu** [mikushimizu/HelloWorld#3]
3つあります。
①バーチャルパットで動かした向きに進ませたい
今はなぜか逆向きに進んでしまってます。

②プレイヤーにバーチャルパットで動かした向きを向かせたい
どこにどうコードを書けばそうなるかわかりません…。

③止まったときは歩行アニメーションを止めたい
アニメーションが使いこなせません

質問大量投げですみません！！！

**Comment by Ayarin226** [comment]
2と3については調べれば文献もたくさんありますし、1については座標周りをきちんと見れば分かりそうです！
一旦こちらも、どうすればいいのか何も分からないのか
何を試して出来なかったのか、も書いてもらえると！

**Comment by mikushimizu** [comment]
①は解決しました！！　優先度的に③とセーブは一旦置いて、まず②を解決させたいです。

PlayerMoveControlerのUpdate内に、バーチャルパットのスティックが倒れた方向を向く命令を書こうとして http://tsubakit1.hateblo.jp/entry/2017/07/03/234224 を読みつつやってみたのですが、
記事にあるCrossPlatformInputではなくSimpleTouchControllerを使っているせいか、うまくいきません。できればCrossPlatformInputではなくSimpleTouchControllerを使いたいですが、記事のスクリプトではusing UnityStandardAssets.CrossPlatformInputと前者の使用を宣言していることも後々詰まってる原因かなと思います。
Update()の中には以下のように記述しました。
// スティックの倒れた向きを向く
		var v2 = CrossPlatformInputManager.GetAxis ("Vertical");
		var h2 = CrossPlatformInputManager.GetAxis ("Horizontal");
		Vector3 direction = new Vector3(h2,0,v2);
		transform.localRotation = Quaternion.LookRotation (direction);
上２行、v2とh2をSimpleTouchControllerのスクリプトから取得できればいけそうな気がするのですが、SimpleTouchControllerに付属しているスクリプトのコードが読み解けません。
どうすればいいでしょうか。

**Comment by Ayarin226** [comment]
①解決できてよかった！
②はおっしゃっている通りで、v2とh2を `SimpleTouchController` から取得出来ればいけます！
そもそもv2とh2がどういう値なのか、は分かったかな？
v2が垂直方向(上下)、h2が水平方向(左右)の入力の値を示しています！
つまり、  `SimpleTouchController` でどのように入力を取っているか分かれば良いわけですね！
ざざっと見た感じだと、 `GetTouchPosition()` で同じような値が取れる気がするのだけどどうでしょうか？

**Comment by mikushimizu** [comment]
// スティックの倒れた向きを向く
		var v2 = leftController.GetTouchPosition.y;
		var h2 = leftController.GetTouchPosition.x;
                Vector3 direction = new Vector3(h2,0,v2);
		transform.localRotation = Quaternion.LookRotation (direction);

でキャラクターの向く方向は操作できました！　ありがとうございます。
ですが何故か移動速度が鈍くなり、更にバーチャルパッドの上半分に向けた際の移動がおかしくなってしました。原因がわかりません…。

**Comment by Ayarin226** [comment]
良かったー！
移動速度と上半分の挙動は書いた部分コメントアウトしたら起きない現象なのかな？
値とってるだけだから関係ないとおもうんだけど……

**Comment by mikushimizu** [comment]
コメントアウトすれば起きません！原因不明です…

**Comment by Ayarin226** [comment]
おぉ、なるほどね
直前に何いじったか覚えてたりしないかな？
`SimpleTouchController` のどこかをいじってしまってそう。
覚えてなかったらgithubに上がってるデータとにらめっこしたら良いかも🙌🏻

**Comment by mikushimizu** [comment]
すみません分かりませんでした…
ちなみにSimpleTouchControllerは変わってなさそうです。

**Comment by Ayarin226** [comment]
なるほど……
ちょっと遅くなってしまうけど夕方の17:00くらいに最新版pushしておいてくれれば見てみます！

**Comment by mikushimizu** [comment]
お忙しいところ申し訳ありません。よろしくお願いします！

**Comment by Ayarin226** [comment]
遅くなってしまってごめんね！
`PlayerMoveController`内で`MovePosition` を使って移動している部分をこんな感じに変更したら良い感じに動きましたー！

`_rigidbody.velocity = new Vector3(leftController.GetTouchPosition.x, 0, leftController.GetTouchPosition.y) * speed; `

`float speed`を良い感じの値に調整したら良いと思います！

`transform.forward` とか、自分の向いている向きに依存している動き方をしていたから、挙動がおかしくなっていたんだと思う……！

**Comment by mikushimizu** [comment]
できました！！！なるほどそうだったんですね…！
ありがとうございます！！！
